INSERT INTO t_p77368943_wiki_bf_debts_starve.wiki_articles (slug,title,category,subcategory,icon,rarity,beli_price,robux_price,fragment_price,description,abilities) VALUES
('dark-blade','Dark Blade','Swords','Легендарный меч','⚔️','mythical',0,1200,0,'Меч Михока — самый мощный меч в Blox Fruits. Получается только от Mihawk или через геймпасс.','Dark Slash, Dark Rush, Soul Guitar'),
('yama','Yama','Swords','Легендарный меч','🗡️','legendary',0,0,500,'Один из лучших мечей для фарма. Огромный радиус атаки и высокий урон.','Great Divide, Death Step Slash, Infernal Slash'),
('tushita','Tushita','Swords','Небесный меч','✨','legendary',0,0,0,'Небесный меч с высоким уроном. Требует квест для получения.','Heavenly Slash, Celestial Pierce, Divine Barrage'),
('true-triple-katana','True Triple Katana','Swords','Легендарный меч','⚔️','legendary',0,0,0,'Улучшенная версия Triple Katana с тремя клинками.','Three Sword Style, Santoryu Rush, Tornado Slash'),
('cursed-dual-katana','Cursed Dual Katana','Swords','Проклятый меч','🔮','epic',0,0,0,'Проклятый меч с уникальным стилем. Требует квест.','Cursed Strike, Dual Slash, Phantom Blade'),
('pole-v2','Pole (Second Form)','Swords','Посох','🪄','epic',0,0,0,'Посох с разблокированной второй формой. Электрические атаки.','Thunder Thrust, Pole Barrage, Electric Slash'),
('gravity-cane','Gravity Cane','Swords','Трость','⚫','rare',0,0,0,'Гравитационная трость. Притягивает противников.','Gravity Pull, Crush, Orbital Strike'),
('trident','Trident','Weapons','Копья','🔱','epic',0,0,0,'Трезубец с мощными атаками дальнего боя.','Trident Throw, Sea Stab, Tidal Surge'),
('shark-anchor','Shark Anchor','Weapons','Якорь','⚓','epic',0,0,0,'Огромный якорь с массовым уроном по области.','Anchor Slam, Spin Smash, Tidal Crush'),
('pipe','Pipe','Weapons','Дубины','🔧','rare',0,0,0,'Труба с простыми но мощными атаками.','Pipe Smash, Pipe Spin, Ground Slam'),
('kabucha','Kabucha','Weapons','Дальнобойное','🎯','rare',0,0,0,'Один из лучших вариантов дальнобойного оружия.','Energy Blast, Rapid Shots, Explosive Round'),
('slingshot','Slingshot','Weapons','Дальнобойное','🏹','common',0,0,0,'Рогатка для атак с дальней дистанции.','Rock Shot, Rapid Fire, Power Shot'),
('death-step','Death Step','Fighting Styles','Ноги','💀','legendary',0,0,0,'Топовый стиль боя. Быстрые удары ногами. Требует Superhuman + квест.','Hellfire Kick, Death Rush, Barrage of Death'),
('superhuman','Superhuman','Fighting Styles','Руки','💪','legendary',0,0,0,'Лучший рукопашный стиль. Открывает Death Step и Godhuman.','Superhuman Combo, Thunderclap, Beast Rush'),
('godhuman','Godhuman','Fighting Styles','Элитный','👊','mythical',0,0,0,'Высший стиль боя. Требует Death Step + Water Kung Fu + Superhuman + Sharkman Karate.','Holy Combo, Godly Barrage, Thunder Clap'),
('electric-claw','Electric Claw','Fighting Styles','Электро','⚡','legendary',0,0,0,'Электрический стиль. Молниеносные атаки и электро-комбо.','Claw Strike, Thunderstorm, Lightning Dash'),
('dark-step','Dark Step','Fighting Styles','Ноги','🌑','rare',150000,0,0,'Тёмный стиль боя. Хорош для начального PvP.','Dark Rush, Shadow Kick, Darkness Barrage'),
('water-kung-fu','Water Kung Fu','Fighting Styles','Вода','💧','uncommon',0,0,0,'Водный стиль кунг-фу. Нужен для создания Godhuman.','Whirlpool, Water Kick, Tsunami Slam'),
('sharkman-karate','Sharkman Karate','Fighting Styles','Вода','🦈','epic',0,0,0,'Стиль боя акулы. Необходим для Godhuman.','Shark Barrage, Vacuum Crush, Water Body'),
('human-v3','Human V3','Races','V3','🧑','common',0,0,0,'Человек V3. Усиленный Instinct и бонусы к урону. Открывается через квест.','Focus, Instinct+, Damage Boost'),
('sky-v3','Sky (Angel) V3','Races','V3','👼','rare',0,0,0,'Небесный ангел V3. Усиленный полёт и небесные атаки.','Angel Leap, Sky Barrage, Holy Rain'),
('fish-v3','Fish V3','Races','V3','🐟','rare',0,0,0,'Рыба V3. Лучший пловец и водные атаки.','Aqua Dash, Deep Dive, Water Burst'),
('mink-v3','Mink V3','Races','V3','🐾','rare',0,0,0,'Зверолюд V3. Электро Дору и скоростные атаки.','Electro, Mink Dash, Thunder Rush'),
('cyborg-v3','Cyborg V3','Races','V3','🤖','epic',0,0,0,'Киборг V3. Лазерные атаки и бронированная защита.','Laser Blast, Iron Skin, Cyborg Rush'),
('ghoul-v3','Ghoul V3','Races','V3','💀','epic',0,0,0,'Упырь V3. Дренаж жизни и тёмные атаки.','Life Drain, Dark Aura, Ghoul Roar'),
('human-v4','Human V4 (2026)','Races','V4','🌟','legendary',0,0,0,'Человек V4 — обновление 2026. Новые пробуждения и усиленный True Instinct.','True Instinct, Power Surge, Final Focus'),
('sky-v4','Sky (Angel) V4 (2026)','Races','V4','✨','legendary',0,0,0,'Ангел V4 — обновление 2026. Небесная трансформация с крыльями.','Divine Wings, Holy Storm, Heavenly Descent'),
('fish-v4','Fish V4 (2026)','Races','V4','🌊','legendary',0,0,0,'Рыба V4 — обновление 2026. Форма морского дракона.','Sea Dragon, Tsunami Wave, Ocean Fury'),
('mink-v4','Mink V4 (2026)','Races','V4','⚡','legendary',0,0,0,'Зверолюд V4 — обновление 2026. Полная форма молнии.','Full Electro, Mink Fury, Thunder God'),
('cyborg-v4','Cyborg V4 (2026)','Races','V4','🔴','legendary',0,0,0,'Киборг V4 — обновление 2026. Полное превращение в боевую машину.','Mech Form, Hyper Laser, Nuclear Core'),
('ghoul-v4','Ghoul V4 (2026)','Races','V4','🖤','legendary',0,0,0,'Упырь V4 — обновление 2026. Абсолютная форма тьмы.','Death Form, Soul Harvest, Dark Explosion')
ON CONFLICT (slug) DO NOTHING;